### ISSUE TITLE
Identify why ESS Global docs are are not up to date

### ISSUE THREAD

**Issue by ColmDC** [DigitalCommons/goth#12]
The autogenerated ESSGlobal documentation which is published [here ](https://dev.vocabs.solidarityeconomy.coop/essglobal/2.1/html-content/essglobal.html#reference)does not reflect the version of ESSGlobal are currently supporting on the bleeding edge.

The latest version uses the label 'Typology', in multiple languages, for the Base Membership Type. Where the documentation has 'Base Membership Type VES'

**Comment by wu-lee** [comment]
map-sse's latest is on the `goth-integration` branch, I need to merge that in properly.

The reason the HTML docs say "Base Membership Type" is because there is a top level `essglobal-vocab.ttl` file ([here]) which describes the non-vocab bits like classes, and tha still calls it that. The vocab itself is titled Typology.  There are some URIs in this top-level file which look wrong too, so it probably needs some work.

[here]: https://github.com/DigitalCommons/map-sse/blob/ica10-draft-locality-vocabs/vocabs/vocab/essglobal-vocab.ttl

**Comment by ColmDC** [comment]
Motivation for this one https://github.com/digitalcommons/open-data/issues/56
