### ISSUE TITLE
Make a Ruby gem

### ISSUE THREAD

**Issue by ThomasDavisonsGit** [DigitalCommons/goth#2]
Turn GOTH into a Ruby gem so that it can more conveniently be installed and called. ("Bundle" may need to get involved)

**Comment by wu-lee** [comment]
These seem to be good starting points.

https://guides.rubygems.org/make-your-own-gem/
https://bundler.io/guides/creating_gem.html


What we'll want to be able to do is list the upcoming goth gem as a dependency of the ESSBLOBAL build project, and then use `bundler` to install it.  To list `goth` as a dependency, the consuming project lists it in a `Gemfile`, along with any other dependencies.  Ordinarily, gems are published on RubyGems.org, but we don't have to do that, as we can [specify the dependency as a direct reference to a project in a Git repository somewhere, or on Github][2]. This saves the hassle of registering on RubyGems and publishing there. However, for that to work the gem needs to have a `Gemspec` file in the root folder of the project. (The docs linked above should elaborate on that.)  The `Gemspec` file describes a gem in a way that `bundler` can understand and use.  Given all that, the user of the consuming project (me) can then run `bundle install` in order to download and install all the dependencies to a local folder accessible to the project's code. These resources are made accessible to a script `$somescript` when run using `bundle exec $somescript`.

So where I want to be is to be able to execute these steps to rebuild the map-sse vocabs with documentation created by `goth`:

    git clone git@github.com:SolidarityEconomyAssociation/map-sse.git
    cd map-sse/generators
    bundle install
    bundle exec ./build
    bundle exec ./redeploy-all

The build script will call a Ruby script [marked in the goth Gemspec file as one to install as an executable][1], supplying the appropriate command-line parameters to direct it to use the appropriate .ttl files in the map-sse project as inputs, and output the resulting html documentatin in a convenient location, for subsequent deployment.

[1]: https://guides.rubygems.org/specification-reference/#executables
[2]: https://bundler.io/man/gemfile.5.html#GIT

**Comment by ThomasDavisonsGit** [comment]
@ColmDC this is the outstanding Goth issue for integrating it into current scripts.

**Comment by wu-lee** [comment]
This is now done as part of the work merged into master, and tagged `v0.1.0`
